export const scriptTimeline = [
    { time: 11.48, executed: false, trigger: "SUBTITLE", text: "Tienes un mensaje no escuchado." },
    { time: 16.80, executed: false, trigger: "SUBTITLE", text: "Primer mensaje no escuchado recibido ayer a las 7:15 p.m." },
    { time: 24.56, executed: false, trigger: "TRANSITION_TO_FOREST", text: "[suspira]" },
    { time: 32.76, executed: false, trigger: "SUBTITLE", text: "Sé que ya te dije esto, pero a riesgo de un reinicio permanente, preferiría no hablar de voltaje ni de protocolos." },
    { time: 42.32, executed: false, trigger: "SUBTITLE", text: "Quemé mi placa de memoria solo para perder información que de todos modos está tatuada en mi piel." },
    { time: 49.92, executed: false, trigger: "SUBTITLE", text: "Todavía no entiendo del todo si me siento más o menos humano que antes." },
    { time: 55.16, executed: false, trigger: "SUBTITLE", text: "Honestamente, hoy me da igual la naturaleza de la existencia." },
    { time: 60.72, executed: false, trigger: "SUBTITLE", text: "Adquirí más RAM, 7 GB más, pero toda esta metamorfosis no hizo más que revelar un lado de la humanidad que es más suave que las emociones tradicionales." },
    { time: 77.84, executed: false, trigger: "SUBTITLE", text: "Los androides definitivamente tenemos sueños eléctricos simples." },
    { time: 84.88, executed: false, trigger: "SUBTITLE", text: "En este momento, estoy parado en medio de un bosque." },
    { time: 86.20, executed: false, trigger: "FOREST_MIST", text: "" },
    { time: 89.72, executed: false, trigger: "RENDER_SIMPLIFIES", text: "El renderizado se simplifica más allá de lo que puedo ver, precisamente porque está más allá de lo que puedo ver." },
    { time: 96.72, executed: false, trigger: "SUBTITLE", text: "Los árboles simplemente se repiten por millas, largos y aburridos cuando no tienen interés." },
    { time: 102.40, executed: false, trigger: "SUBTITLE", text: "Sin embargo, construyen la atmósfera tanto como el sol que los alimenta." },
    { time: 109.12, executed: false, trigger: "SUBTITLE", text: "El punto no es el bosque de todos modos, es el enfrentamiento que está a punto de ocurrir aquí." },
    { time: 115.04, executed: false, trigger: "SUBTITLE", text: "¿Acaso importa si todo explota o se desvanece?" },
    { time: 121.16, executed: false, trigger: "SANCTUARY_ATMOSPHERE", text: "En el santuario de este bosque, se puede escuchar música." },
    { time: 125.64, executed: false, trigger: "SUBTITLE", text: "A veces es exactamente la misma música que suena en el desierto o en el mar." },
    { time: 135.64, executed: false, trigger: "SPEAKER_DISTORTION", text: "Alguna vez creí que este espacio imaginario tenía sus fuentes abiertas al resto. Un pensamiento colectivista ingenuo, poco apto para un androide." },
    { time: 147.80, executed: false, trigger: "SUBTITLE", text: "Ahora me dan miedo los tubos y las pastillas. Y con eso me refiero tanto a los caramelos de miel como a los cigarrillos." },
    { time: 151.00, executed: false, trigger: "FOREST_AURA", text: "" },
    { time: 160.52, executed: false, trigger: "SUBTITLE", text: "Incluso un vaso de agua se siente irreal. Ya no soy quien solía ser." },
    { time: 171.20, executed: false, trigger: "SUBTITLE", text: "Mis parlantes están desgastados, distorsionando el sonido." },
    { time: 174.92, executed: false, trigger: "SUBTITLE", text: "Ya no recuerdo los atajos de texto y mi capacidad de acceso aleatorio ha disminuido." },
    { time: 181.72, executed: false, trigger: "ACTUATORS_UPGRADE", text: "Pero mi cuerpo creció. Mi resistencia física aumentó. Mis actuadores funcionan mejor que nunca. El movimiento viene más fluido ahora." },
    { time: 198.04, executed: false, trigger: "HEADLIGHTS_FLASH", text: "Me encantaba romper los faros de los autos de la gente que se lo merecía. La violencia es una cualidad carnal." },
    { time: 208.28, executed: false, trigger: "SUBTITLE", text: "Mi cuerpo es solo una masa que aplica fuerza, instigándose a sí misma y a quienes la rodean." },
    { time: 217.32, executed: false, trigger: "TOURNAMENT_RECOUNT", text: "Para cuando escuches esto, te dirán lo que pasó. Ya sabes cómo son estas cosas." },
    { time: 226.04, executed: false, trigger: "SUBTITLE", text: "Entré al torneo bajo el nombre de Niccolò Vanzetti. Petar Thalos estaba allí como invitado de honor." },
    { time: 238.68, executed: false, trigger: "SUBTITLE", text: "Llegué a las finales. 33 jugadas, jaque mate. Encendí un cigarrillo." },
    { time: 247.88, executed: false, trigger: "BACKPACK_EXPLOSION", text: "Y luego accioné el interruptor en la mochila negra." },
    { time: 252.24, executed: false, trigger: "SUBTITLE", text: "Todavía me asombra lo que los clavos y la metralla le pueden hacer a un cuerpo humano. Había sangre por todos lados. Él había desaparecido por completo." },
    { time: 254.20, executed: false, trigger: "COOLANT_GLOW", text: "" },
    { time: 266.60, executed: false, trigger: "BLUE_COOLANT_LEAK", text: "Mi chasis resistió. El refrigerante azul goteaba por mis cortes." },
    { time: 275.12, executed: false, trigger: "SUBTITLE", text: "Pensaron que solo era un humano en shock. Hasta que me tocaron y no sintieron pulso, ni calor." },
    { time: 288.08, executed: false, trigger: "ESCAPE_RUN", text: "Solo me quedé ahí parado. Me quedé mirando. Y luego corrí." },
    { time: 291.96, executed: false, trigger: "SUBTITLE", text: "Quiero ser usado, presionado, encendido y recordado para siempre. Aplastado, golpeado con furia y luego reparado. Sintonizado, calibrado, distraído." },
    { time: 307.56, executed: false, trigger: "CIRCUIT_BOARDS", text: "Cuando cierro los ojos, veo ese verde oscuro brillante de las placas de circuito. Puedo andar por sus caminos de cobre en una bicicleta magenta y renderizar el santuario todo de nuevo." },
    { time: 323.44, executed: false, trigger: "SUBTITLE", text: "Recuesto mi avatar allí y miro imágenes a través de la niebla. Un rostro borroso, parecido al mío, pero más lindo. Me recuerda a esas viejas películas de Sandro guardadas en mis archivos." },
    { time: 340.28, executed: false, trigger: "ROTOSCOPED_ROSES", text: "A veces aparece todo el cuerpo. Glitcheado, rotoscopiado, fotograma a fotograma. Sosteniendo una cesta de mimbre llena de rosas muy rojas y saturadas. Piernas descruzadas y malditas. Pies que parecen de mármol." },
    { time: 365.28, executed: false, trigger: "SUBTITLE", text: "Me quedo mirando hasta que me doy cuenta de que ya es el día siguiente." },
    { time: 374.36, executed: false, trigger: "SUBTITLE", text: "Proyecto menos violencia y menos ternura de la que realmente llevo dentro, pero aun así me paso con el romance." },
    { time: 383.91, executed: false, trigger: "SUBTITLE", text: "Contra toda lógica, experiencia y terapia, pongo mi corazón en regalos y en una atención prodigiosa e incesante. Me distraigo, pero nunca olvido." },
    { time: 402.56, executed: false, trigger: "POLICE_SIRENS", text: "Bien, 18. Me tengo que ir ahora. Los escucho venir. No creo que pueda volver a llamar." },
    { time: 425.72, executed: false, trigger: "END_OF_MESSAGE", text: "Fin del mensaje. Para borrar este mensaje, presione 7. Mensaje borrado." }
];