export const scriptTimeline = [
    { time: 11.48, executed: false, trigger: "SUBTITLE", text: "Tienes un mensaje no escuchado." },
    { time: 16.80, executed: false, trigger: "SUBTITLE", text: "Primer mensaje no escuchado, <br> enviado ayer a las 7:15 p.m." },
    { time: 24.00, executed: false, trigger: "TRANSITION_TO_FOREST", text: "" },
    { time: 32.759, executed: false, trigger: "SUBTITLE", text: "Sé que ya te lo dije, pero a riesgo de un reinicio permanente," },
    { time: 36, executed: false, trigger: "SUBTITLE", text: "Prefiero no hablar de voltaje ni de protocolos." },
    { time: 42.32, executed: false, trigger: "SUBTITLE", text: "Quemé mi placa de memoria solo para perder información <br> que de todos modos está tatuada en mi piel." },
    { time: 49.92, executed: false, trigger: "SUBTITLE", text: "Aún no entiendo del todo si me siento más o menos <br> humano que antes." },
    { time: 55, executed: false, trigger: "SUBTITLE", text: "Honestamente, hoy no podría importarme menos la naturaleza de la existencia." },
    { time: 61, executed: false, trigger: "SUBTITLE", text: "Adquirí más RAM, 7 GB más, pero toda esta metamorfosis..." },
    { time: 66, executed: false, trigger: "SHOW_DNA_HOLOGRAM", text: "...no hizo más que revelar un lado de la humanidad <br> más amable que las emociones tradicionales." },
    { time: 77.84, executed: false, trigger: "SUBTITLE", text: "Nosotros, los androides, definitivamente tenemos <br> sueños eléctricos y simples." },
    { time: 84, executed: false, trigger: "SUBTITLE", text: "Ahora mismo, estoy en el medio de un bosque." },
    { time: 90, executed: false, trigger: "SUBTITLE", text: "El renderizado se simplifica más allá de lo que puedo ver, <br> precisamente porque está más allá de mi vista." },
    { time: 95, executed: false, trigger: "SUBTITLE", text: "Los árboles simplemente se repiten por kilómetros, <br> largos y aburridos cuando no generan ningún interés." },
    { time: 101, executed: false, trigger: "SUBTITLE", text: "Sin embargo, construyen la atmósfera <br> tanto como el sol que los alimenta." },
    { time: 109.12, executed: false, trigger: "SUBTITLE", text: "De todos modos, el punto no es el bosque, <br> es la confrontación que está por ocurrir aquí." },
    { time: 115, executed: false, trigger: "SUBTITLE", text: "¿Acaso importa si todo explota o se desvanece?" },
    { time: 121.16, executed: false, trigger: "SUBTITLE", text: "En el santuario de este bosque, puedes escuchar música." },
    { time: 126, executed: false, trigger: "SUBTITLE", text: "A veces es exactamente la misma música <br> que suena en el desierto o en el mar." },
    { time: 135.64, executed: false, trigger: "SUBTITLE", text: "Alguna vez creí que este espacio imaginario <br> tenía sus fuentes abiertas al resto." },
    { time: 141, executed: false, trigger: "SUBTITLE", text: "Un pensamiento colectivista ingenuo, <br> poco apropiado para un androide." },
    { time: 147.80, executed: false, trigger: "SUBTITLE", text: "Ahora me encuentro asustado <br> de los tubos y las pastillas." },
    { time: 150, executed: false, trigger: "SUBTITLE", text: "Y con eso, me refiero tanto a <br> los caramelos de miel como a los cigarrillos." },
    { time: 160.52, executed: false, trigger: "SUBTITLE", text: "Incluso un vaso de agua parece irreal." },
    { time: 167, executed: false, trigger: "SUBTITLE", text: "Ya no soy quien solía ser." },
    { time: 171, executed: false, trigger: "SPEAKER_DISTORTION", text: "Mis altavoces están desgastados, <br> distorsionando el sonido." },
    { time: 175, executed: false, trigger: "SUBTITLE", text: "Ya no recuerdo los atajos de texto, <br> y mi capacidad de acceso aleatorio ha disminuido." },
    { time: 182, executed: false, trigger: "SUBTITLE", text: "Pero mi cuerpo creció. <br> Mi resistencia física aumentó." },
    { time: 187, executed: false, trigger: "SUBTITLE", text: "Mis actuadores funcionan mejor que nunca. <br> El movimiento ahora es más fluido." },
    { time: 198.04, executed: false, trigger: "HEADLIGHTS_FLASH", text: "Solía encantarme destrozar los faros de los autos <br> de las personas que se lo merecían." },
    { time: 205, executed: false, trigger: "SUBTITLE", text: "La violencia es una cualidad carnal." },
    { time: 209, executed: false, trigger: "GIANT_SPHERE", text: "Mi cuerpo es solo una masa que aplica fuerza, <br> instigándose a sí misma y a los que la rodean." },
    { time: 217.32, executed: false, trigger: "SUBTITLE", text: "Para cuando escuches esto, <br> te habrán contado lo que pasó." },
    { time: 221.92, executed: false, trigger: "SUBTITLE", text: "Ya sabes cómo son estas cosas." },
    { time: 226.04, executed: false, trigger: "SUBTITLE", text: "Entré al torneo bajo el nombre de Niccola Vanzetti." },
    { time: 232.40, executed: false, trigger: "SUBTITLE", text: "Petar Thalos estaba allí como invitado de honor." },
    { time: 238.68, executed: false, trigger: "SUBTITLE", text: "Llegué a la final. 33 movimientos. Jaque mate." },
    { time: 244.48, executed: false, trigger: "SUBTITLE", text: "Encendí un cigarrillo." },
    { time: 247.88, executed: false, trigger: "BACKPACK_EXPLOSION", text: "Y luego presioné el interruptor en la mochila negra." },
    { time: 250, executed: false, trigger: "TOURNAMENT_RECOUNT", text: "" },
    { time: 252, executed: false, trigger: "SUBTITLE", text: "Todavía me sorprende lo que los clavos y la metralla <br> pueden hacerle a un cuerpo humano." },
    { time: 259.04, executed: false, trigger: "SUBTITLE", text: "Había sangre por todas partes. <br> Él había desaparecido por completo." },
    { time: 266.64, executed: false, trigger: "SUBTITLE", text: "Mi chasis resistió. <br> Refrigerante azul goteaba por mis cortes." },
    { time: 275.12, executed: false, trigger: "SUBTITLE", text: "Pensaron que solo era un humano en estado de shock." },
    { time: 278, executed: false, trigger: "SUBTITLE", text: "Hasta que me tocaron y no sintieron pulso, ni calor." },
    { time: 283, executed: false, trigger: "SUBTITLE", text: "Me quedé ahí parado, mirando. <br> Luego corrí." },
    { time: 291.96, executed: false, trigger: "SUBTITLE", text: "Quiero ser usado, presionado, encendido <br> y recordado para siempre." },
    { time: 298, executed: false, trigger: "SUBTITLE", text: "Aplastado, golpeado con rabia y luego reparado. <br> Afinado, calibrado, distraído." },
    { time: 307.56, executed: false, trigger: "CIRCUIT_BOARDS", text: "Cuando cierro los ojos, veo ese oscuro y <br> brillante verde de las placas de circuito." },
    { time: 314, executed: false, trigger: "SUBTITLE", text: "Puedo recorrer sus caminos de cobre en una bicicleta magenta y renderizar el santuario otra vez." },
    { time: 323.44, executed: false, trigger: "SUBTITLE", text: "Acuesto mi avatar allí abajo y <br> miro imágenes a través de la niebla." },
    { time: 329, executed: false, trigger: "ROSE_SKULL", text: "Un rostro borroso, parecido al mío, pero más bonito." },
    { time: 334, executed: false, trigger: "SUBTITLE", text: "Me recuerda a esas viejas películas de Sandro <br> guardadas en mis archivos." },
    { time: 340.28, executed: false, trigger: "SUBTITLE", text: "A veces aparece el cuerpo entero. <br> Glitcheado, rotoscopiado, cuadro por cuadro." },
    { time: 353.56, executed: false, trigger: "SUBTITLE", text: "Sosteniendo una cesta de mimbre llena de rosas muy rojas y saturadas." },
    { time: 356.96, executed: false, trigger: "SUBTITLE", text: "Piernas descruzadas y malditas. <br> Pies que parecen de mármol." },
    { time: 365.28, executed: false, trigger: "SUBTITLE", text: "Sigo mirando hasta que me doy cuenta <br> de que ya es el día siguiente." },
    { time: 374.36, executed: false, trigger: "SUBTITLE", text: "Proyecto menos violencia y menos ternura <br> de la que realmente llevo por dentro." },
    { time: 379.04, executed: false, trigger: "SUBTITLE", text: "Pero igual exagero con el romance." },
    { time: 383.919, executed: false, trigger: "SUBTITLE", text: "Contra toda lógica, experiencia y <br> terapia, pongo mi corazón en regalos..." },
    { time: 388.84, executed: false, trigger: "SUBTITLE", text: "...y en una prodigiosa e incesante atención." },
    { time: 395.52, executed: false, trigger: "SUBTITLE", text: "Me distraigo, pero nunca olvido." },
    { time: 400, executed: false, trigger: "SPOTLIGHT_ON", text: "" },
    { time: 402.56, executed: false, trigger: "SUBTITLE", text: "Bueno, 18. Me tengo que ir." },
    { time: 405, executed: false, trigger: "POLICE_SIRENS", text: "" },
    { time: 408.32, executed: false, trigger: "SUBTITLE", text: "Los escucho venir." },
    { time: 414.00, executed: false, trigger: "SUBTITLE", text: "No creo que pueda volver a llamarte." },
    { time: 423.72, executed: false, trigger: "END_OF_MESSAGE", text: "" },
    { time: 425.72, executed: false, trigger: "SUBTITLE", text: "Fin del mensaje. <br> Para borrar este mensaje, presione 7." },
    { time: 430.56, executed: false, trigger: "SUBTITLE", text: "Mensaje borrado." },
    { time: 438, executed: false, trigger: "MOVIE_CREDITS", text: "" }

];